package com.anode.tool.service;

import java.io.Serializable;

/**
 * Factory interface for generating and managing unique identifiers.
 * @param <T> the type of identifiers generated by this factory
 */
public interface IdFactory<T extends Serializable> {
    /**
     * Generates a new unique identifier.
     * @return a new unique identifier
     */
    public T newId();

    /**
     * Marks an identifier as consumed or reserved.
     * @param id the identifier to consume
     */
    public void consumeId(T id);
}

